version: '3.9'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: todo_db
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Asd1234!
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data:
